### PR TITLE
(fix): typehint

### PR DESCRIPTION
**Pull request by pepperfm**
Hi there!

Here ive got an error, when trying to pass closure as parameter.

May be here should be inversed changes? (remove callable type from method params, not from properties)

### CODE REVIEW

**Comment by chrisreedio** [comment]
Can you explain these changes @pepperfm ?

You should have already been able to pass in a closure.

**Comment by pepperfm** [comment]
> You should have already been able to pass in a closure.

function can accept the closure, right
but the class properties is only can be string or null: `protected ?string $loginRoute = null;`

so when i trying to pass closure, ive got an error

**Comment by pepperfm** [comment]
> so when i trying to pass closure, ive got an error

on class-property level, not on function agrs

**Review by chrisreedio — APPROVED** [review]
Changes look ok to me!

**Pull request merged**
